export enum TYPES_OF_CHAT_CONFIG {
  PROMPT_TEMPLATE = "PROMPT_TEMPLATE",
  TEMPERATURE = "TEMPERATURE",
  RETRIEVE_COUNT = "RETRIEVE_COUNT",
  USE_SEMANTIC_RANKER = "USE_SEMANTIC_RANKER",
  USE_SEMANTIC_CAPTIONS = "USE_SEMANTIC_CAPTIONS",
  SHOULD_STREAM = "SHOULD_STREAM",
  EXCLUDE_CATEGORY = "EXCLUDE_CATEGORY",
  SUGGEST_FOLLOWUP_QUESTIONS = "SUGGEST_FOLLOWUP_QUESTIONS",
  USE_OID_SECURITY_FILTER = "USE_OID_SECURITY_FILTER",
  USE_GROUPS_SECURITY_FILTER = "USE_GROUPS_SECURITY_FILTER"
}

export enum USE_CASES {
  THEME_1 = "THEME_1",
  THEME_2 = "THEME_2",
  THEME_3 = "THEME_3"
}
